# Generated by Django 6.0.3 on 2026-03-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablename', '0003_remove_employee_email_remove_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
