# Generated by Django 6.0.3 on 2026-04-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablename', '0004_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('mason', 'Mason'), ('electrician', 'Electrician'), ('team_member', 'Team Member'), ('admin', 'Admin'), ('hr', 'HR')], max_length=20),
        ),
    ]
