# Generated by Django 6.0.3 on 2026-04-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablename', '0006_remove_userprofile_email_salary_daily_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='basic',
            new_name='computed_salary',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='daily_rate',
            new_name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='days_worked',
        ),
        migrations.AddField(
            model_name='salary',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='tablename.site'),
        ),
        migrations.AddField(
            model_name='request',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablename.site'),
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
