# Generated by Django 6.0.3 on 2026-04-08 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablename', '0007_site_rename_basic_salary_computed_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tue', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('wed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('thu', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fri', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sun', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='tablename.employee')),
            ],
            options={
                'unique_together': {('employee', 'week_start')},
            },
        ),
    ]
